import csv
import pandas as pd
import os

list_syntax = ["python3 main.py --dataloader 'tcga-mpg' --arch MuAtMotifPositionGESF --input-data-dir '/scratch/project_2001668/data/tcga/tokenized/' --output-train-dir '/scratch/project_2001668/primasan/ckpt_epi/' --save-ckpt-dir '/scratch/project_2001668/primasan/ckpt_epi/' --batch-size 8 --epoch 100 --n-class 23 --block-size 300 --n-layer 1 --n-head 1 --n-emb 256 --fold 1 --mut-type SNV+MNV+indel --trainsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_train.csv' --valsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_val.csv' --classinfo-file '/users/primasan/projects/muat/dataset_utils/classinfo_tcga_epi.csv' --tag 'tcga_mpge' --get-motif --get-position --get-ges --train",
"python3 main.py --dataloader 'tcga-mpg' --arch MuAtEpiF --input-data-dir '/scratch/project_2001668/data/tcga/tokenized/' --output-train-dir '/scratch/project_2001668/primasan/ckpt_epi/' --save-ckpt-dir '/scratch/project_2001668/primasan/ckpt_epi/' --batch-size 8 --epoch 100 --n-class 23 --block-size 300 --n-layer 1 --n-head 1 --n-emb 256 --epi-emb 2 --fold 1 --mut-type SNV+MNV+indel --trainsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_train.csv' --valsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_val.csv' --classinfo-file '/users/primasan/projects/muat/dataset_utils/classinfo_tcga_epi.csv' --tag 'tcga_mpge' --get-epi --train",
"python3 main.py --dataloader 'tcga-mpg' --arch MuAtEpiF --input-data-dir '/scratch/project_2001668/data/tcga/tokenized/' --output-train-dir '/scratch/project_2001668/primasan/ckpt_epi/' --save-ckpt-dir '/scratch/project_2001668/primasan/ckpt_epi/' --batch-size 8 --epoch 100 --n-class 23 --block-size 300 --n-layer 1 --n-head 1 --n-emb 256 --epi-emb 4 --fold 1 --mut-type SNV+MNV+indel --trainsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_train.csv' --valsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_val.csv' --classinfo-file '/users/primasan/projects/muat/dataset_utils/classinfo_tcga_epi.csv' --tag 'tcga_mpge' --get-epi --train",
"python3 main.py --dataloader 'tcga-mpg' --arch MuAtEpiF --input-data-dir '/scratch/project_2001668/data/tcga/tokenized/' --output-train-dir '/scratch/project_2001668/primasan/ckpt_epi/' --save-ckpt-dir '/scratch/project_2001668/primasan/ckpt_epi/' --batch-size 8 --epoch 100 --n-class 23 --block-size 300 --n-layer 1 --n-head 1 --n-emb 256 --epi-emb 4 --fold 1 --mut-type SNV+MNV+indel --trainsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_train.csv' --valsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_val.csv' --classinfo-file '/users/primasan/projects/muat/dataset_utils/classinfo_tcga_epi.csv' --tag 'tcga_mpge' --get-epi --train",
"python3 main.py --dataloader 'tcga-mpg' --arch MuAtMotifPositionGESEpiF_OneEpiEmb --input-data-dir '/scratch/project_2001668/data/tcga/tokenized/' --output-train-dir '/scratch/project_2001668/primasan/ckpt_epi/' --save-ckpt-dir '/scratch/project_2001668/primasan/ckpt_epi/' --epoch 100 --n-class 23 --block-size 300 --n-layer 1 --n-head 1 --n-emb 256 --fold 1 --epi-emb 2 --batch-size 8 --mut-type SNV+MNV+indel --trainsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_train.csv' --valsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_val.csv' --classinfo-file '/users/primasan/projects/muat/dataset_utils/classinfo_tcga_epi.csv' --tag 'tcga_mpge' --get-motif --get-position --get-ges --get-epi --train",
"python3 main.py --dataloader 'tcga-mpg' --arch MuAtMotifPositionGESEpiF_OneEpiEmb --input-data-dir '/scratch/project_2001668/data/tcga/tokenized/' --output-train-dir '/scratch/project_2001668/primasan/ckpt_epi/' --save-ckpt-dir '/scratch/project_2001668/primasan/ckpt_epi/' --epoch 100 --n-class 23 --block-size 300 --n-layer 1 --n-head 1 --n-emb 256 --fold 1 --epi-emb 4 --batch-size 8 --mut-type SNV+MNV+indel --trainsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_train.csv' --valsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_val.csv' --classinfo-file '/users/primasan/projects/muat/dataset_utils/classinfo_tcga_epi.csv' --tag 'tcga_mpge' --get-motif --get-position --get-ges --get-epi --train",
"python3 main.py --dataloader 'tcga-mpg' --arch MuAtMotifPositionGESEpiF_OneEpiEmb --input-data-dir '/scratch/project_2001668/data/tcga/tokenized/' --output-train-dir '/scratch/project_2001668/primasan/ckpt_epi/' --save-ckpt-dir '/scratch/project_2001668/primasan/ckpt_epi/' --epoch 100 --n-class 23 --block-size 300 --n-layer 1 --n-head 1 --n-emb 256 --fold 1 --epi-emb 8 --batch-size 8 --mut-type SNV+MNV+indel --trainsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_train.csv' --valsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_val.csv' --classinfo-file '/users/primasan/projects/muat/dataset_utils/classinfo_tcga_epi.csv' --tag 'tcga_mpge' --get-motif --get-position --get-ges --get-epi --train",
"python3 main.py --dataloader 'tcga-mpg' --arch MuAtMotifPositionGESEpiF_EpiCompress --input-data-dir '/scratch/project_2001668/data/tcga/tokenized/' --output-train-dir '/scratch/project_2001668/primasan/ckpt_epi/' --save-ckpt-dir '/scratch/project_2001668/primasan/ckpt_epi/' --epoch 100 --n-class 23 --block-size 300 --n-layer 1 --n-head 1 --n-emb 256 --fold 1 --epi-emb 2 --batch-size 8 --mut-type SNV+MNV+indel --trainsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_train.csv' --valsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_val.csv' --classinfo-file '/users/primasan/projects/muat/dataset_utils/classinfo_tcga_epi.csv' --tag 'tcga_mpge' --get-motif --get-position --get-ges --get-epi --train",
"python3 main.py --dataloader 'tcga-mpg' --arch MuAtMotifPositionGESEpiF_EpiCompress --input-data-dir '/scratch/project_2001668/data/tcga/tokenized/' --output-train-dir '/scratch/project_2001668/primasan/ckpt_epi/' --save-ckpt-dir '/scratch/project_2001668/primasan/ckpt_epi/' --epoch 100 --n-class 23 --block-size 300 --n-layer 1 --n-head 1 --n-emb 256 --fold 1 --epi-emb 4 --batch-size 8 --mut-type SNV+MNV+indel --trainsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_train.csv' --valsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_val.csv' --classinfo-file '/users/primasan/projects/muat/dataset_utils/classinfo_tcga_epi.csv' --tag 'tcga_mpge' --get-motif --get-position --get-ges --get-epi --train",
"python3 main.py --dataloader 'tcga-mpg' --arch MuAtMotifPositionGESEpiF_EpiCompress --input-data-dir '/scratch/project_2001668/data/tcga/tokenized/' --output-train-dir '/scratch/project_2001668/primasan/ckpt_epi/' --save-ckpt-dir '/scratch/project_2001668/primasan/ckpt_epi/' --epoch 100 --n-class 23 --block-size 300 --n-layer 1 --n-head 1 --n-emb 256 --fold 1 --epi-emb 8 --batch-size 8 --mut-type SNV+MNV+indel --trainsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_train.csv' --valsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_val.csv' --classinfo-file '/users/primasan/projects/muat/dataset_utils/classinfo_tcga_epi.csv' --tag 'tcga_mpge' --get-motif --get-position --get-ges --get-epi --train",
"python3 main.py --dataloader 'tcga-mpg' --arch MuAtEpiF_EpiCompress --input-data-dir '/scratch/project_2001668/data/tcga/tokenized/' --output-train-dir '/scratch/project_2001668/primasan/ckpt_epi/' --save-ckpt-dir '/scratch/project_2001668/primasan/ckpt_epi/' --epoch 100 --n-class 23 --block-size 300 --n-layer 1 --n-head 1 --n-emb 256 --fold 1 --epi-emb 2 --batch-size 8 --mut-type SNV+MNV+indel --trainsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_train.csv' --valsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_val.csv' --classinfo-file '/users/primasan/projects/muat/dataset_utils/classinfo_tcga_epi.csv' --tag 'tcga_mpge' --get-epi --train",
"python3 main.py --dataloader 'tcga-mpg' --arch MuAtEpiF_EpiCompress --input-data-dir '/scratch/project_2001668/data/tcga/tokenized/' --output-train-dir '/scratch/project_2001668/primasan/ckpt_epi/' --save-ckpt-dir '/scratch/project_2001668/primasan/ckpt_epi/' --epoch 100 --n-class 23 --block-size 300 --n-layer 1 --n-head 1 --n-emb 256 --fold 1 --epi-emb 4 --batch-size 8 --mut-type SNV+MNV+indel --trainsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_train.csv' --valsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_val.csv' --classinfo-file '/users/primasan/projects/muat/dataset_utils/classinfo_tcga_epi.csv' --tag 'tcga_mpge' --get-epi --train",
"python3 main.py --dataloader 'tcga-mpg' --arch MuAtEpiF_EpiCompress --input-data-dir '/scratch/project_2001668/data/tcga/tokenized/' --output-train-dir '/scratch/project_2001668/primasan/ckpt_epi/' --save-ckpt-dir '/scratch/project_2001668/primasan/ckpt_epi/' --epoch 100 --n-class 23 --block-size 300 --n-layer 1 --n-head 1 --n-emb 256 --fold 1 --epi-emb 4 --batch-size 8 --mut-type SNV+MNV+indel --trainsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_train.csv' --valsplit-file '/users/primasan/projects/muat/dataset_utils/tcgaepi_val.csv' --classinfo-file '/users/primasan/projects/muat/dataset_utils/classinfo_tcga_epi.csv' --tag 'tcga_mpge' --get-epi --train"
]

for j in range(0,len(list_syntax)):

    string ="#!/bin/bash\n#SBATCH --account=project_2001668\n#SBATCH --partition=gpu\n#SBATCH --ntasks=1\n#SBATCH --cpus-per-task=1\n#SBATCH --mem=64G\n#SBATCH --time=72:00:00\n#SBATCH --gres=gpu:v100:1\n#SBATCH --output=/scratch/project_2001668/primasan/.out/R-%x.%j.out\n#SBATCH --error=/scratch/project_2001668/primasan/.out/R-%x.%j.err\n\n"  
    command = 'srun ' + list_syntax[j]

    string_logs = str(j+1)

    completeName = "/users/primasan/projects/muat/one_execution-" + string_logs +".sh"
    file1 = open(completeName, "w")
    toFile = string + command
    file1.write(toFile)
    file1.close()







